# Generated by Django 5.0.2 on 2024-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('descriptiopn', models.TextField()),
                ('composition', models.TextField()),
                ('category', models.CharField(choices=[('CR', 'Curd'), ('MI', 'Milk'), ('LS', 'Lassi'), ('BU', 'Butter'), ('CH', 'Cheese'), ('MS', 'Miklshake'), ('PA', 'Paneer'), ('IC', 'Ice Cream'), ('OT', 'Others')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
