# Generated by Django 5.0.2 on 2024-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('MI', 'Milk'), ('LS', 'Lassi'), ('BU', 'Butter'), ('CH', 'Cheese'), ('MS', 'Miklshake'), ('PA', 'Paneer'), ('IC', 'Ice Cream'), ('GH', 'Ghee'), ('OT', 'Others')], max_length=2),
        ),
    ]
