# Generated by Django 5.0.2 on 2024-02-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CH', 'Cheese'), ('MS', 'Miklshake'), ('PA', 'Paneer'), ('IC', 'Ice Cream'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
