# Generated by Django 5.0.2 on 2024-02-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptiopn',
            new_name='description',
        ),
    ]
