# Generated by Django 5.0.2 on 2024-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
