# Generated by Django 5.0.2 on 2024-02-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
